/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.sun.net.httpserver.Authenticator;
import controladores.producto_controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Producto;

/**
 *
 * @author B09S206est
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "NOMBRE", "CANTIDAD", "PRECIO"}, 0
        );
        
        tbl_productos.setModel(modelo);
    }

    producto_controller productoControlador = new producto_controller();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_productId = new javax.swing.JTextField();
        txt_productCant = new javax.swing.JTextField();
        txt_productPrec = new javax.swing.JTextField();
        lbl_productId = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_productName = new javax.swing.JLabel();
        txt_productName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        bt_buscarProduct = new javax.swing.JButton();
        bt_agregarProduct = new javax.swing.JButton();
        bt_eliminarProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al gestor de inventarios");

        txt_productCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productCantActionPerformed(evt);
            }
        });

        lbl_productId.setText("Id");

        lbl.setText("Cantidad");

        jLabel4.setText("Precio");

        lbl_productName.setText("Nombre");

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_productos);

        bt_buscarProduct.setText("Buscar Producto");
        bt_buscarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarProductActionPerformed(evt);
            }
        });

        bt_agregarProduct.setText("Agregar Producto");
        bt_agregarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarProductActionPerformed(evt);
            }
        });

        bt_eliminarProduct.setText("Eliminar Producto");
        bt_eliminarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl)
                            .addComponent(lbl_productName)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbl_productId)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_productId, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_productPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_productCant, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_buscarProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_agregarProduct)
                        .addGap(34, 34, 34)
                        .addComponent(bt_eliminarProduct)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_agregarProduct)
                            .addComponent(bt_eliminarProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(bt_buscarProduct)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_productId))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_productCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_productPrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl)))
                            .addComponent(lbl_productName)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarProductActionPerformed
       
        boolean seGuardo = productoControlador.agregar( crear_producto());
        
        if(seGuardo){
            JOptionPane.showMessageDialog(this, "Se guardo el producto");
        }else{
            JOptionPane.showMessageDialog(this, "Hubo un error en el guardado");
        }
        mostrarProductos();
        clear();
        
    }//GEN-LAST:event_bt_agregarProductActionPerformed

    private void bt_eliminarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarProductActionPerformed
        // TODO add your handling code here:
        
        String id = txt_productId.getText();
        
        boolean eliminado = productoControlador.eliminar(id);
        if(eliminado){
            JOptionPane.showMessageDialog(this, "Producto eliminado");
        }else{
            JOptionPane.showMessageDialog(this, "Hubo un error en la eliminacion");
        }
        mostrarProductos();
        clear();
        
    }//GEN-LAST:event_bt_eliminarProductActionPerformed

    private void bt_buscarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarProductActionPerformed

    }//GEN-LAST:event_bt_buscarProductActionPerformed

    private void txt_productCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productCantActionPerformed


    public Producto crear_producto(){
        
        Producto producto = new Producto();
        
        producto.setId(txt_productId.getText());
        producto.setNombre(txt_productName.getText());
        producto.setPrecio( Double.parseDouble(txt_productPrec.getText()));
        producto.setStock(Integer.parseInt(txt_productCant.getText()));
        return producto;
    }
    
    
    public void clear()
    {
        txt_productId.setText("");
        txt_productName.setText("");
        txt_productPrec.setText("");
        txt_productCant.setText("");
    }
    
    
    public void mostrarProductos() {
    // Limpiar la tabla antes de volver a llenarla
    DefaultTableModel modelo = (DefaultTableModel) tbl_productos.getModel();
    modelo.setRowCount(0);

    // Obtener la lista del controlador
    ArrayList<Producto> lista = productoControlador.getProductos(); // o controller.getProductos() si usas getter

    // Llenar fila por fila
    for (Producto p : lista) {
        Object[] fila = {
            p.getId(),
            p.getNombre(),
            p.getStock(),
            p.getPrecio()
        };
        modelo.addRow(fila);
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregarProduct;
    private javax.swing.JButton bt_buscarProduct;
    private javax.swing.JButton bt_eliminarProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl_productId;
    private javax.swing.JLabel lbl_productName;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTextField txt_productCant;
    private javax.swing.JTextField txt_productId;
    private javax.swing.JTextField txt_productName;
    private javax.swing.JTextField txt_productPrec;
    // End of variables declaration//GEN-END:variables
}
